version: "3.7"

  
services:
  ### Push Service Server rfc8030 #########################################
  app:
    build: ./app
    ports:
      - "4311:4311"
    environment: 
      - APP_NAME=${APP_NAME}
    volumes:
      - '${APP_CODE_PATH_HOST}:/app'
      - '${APP_CODE_PATH_HOST}/../recursos:/recursos'
  bash:
    image: 'bash'
    build: ./bash
    volumes: 
      - '../src:/app'
    
### Caddy Server #########################################
  caddy:
    image: 'abiosoft/caddy'
    build: ./caddy
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ${CADDY_CONFIG_PATH}:/etc/caddy
      - ${CADDY_HOST_LOG_PATH}:/var/log/caddy
      - ${DATA_PATH_HOST}:/app/storage/.caddy
      - '${APP_CODE_PATH_HOST}/:/app'
      - '${APP_CODE_PATH_HOST}/../recursos:/recursos'
    ports:
      - "${CADDY_HOST_HTTP_PORT}:80"
      - "${CADDY_HOST_HTTPS_PORT}:443"
    depends_on:
      - app
    
  
   
